language: java
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - chmod +x ./mvnw
script:
  - mvn clean package -DskipTests=true docker:build
  - docker login -u="edidada" -p="5Edidada"
  - docker push edidada//eureka-server-test:0.0.4-SNAPSHOT